"""Added MetaData

Revision ID: 9465f557279f
Revises: 19324b31bda7
Create Date: 2024-05-10 12:38:02.833320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9465f557279f'
down_revision = '19324b31bda7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_data',
    sa.Column('Idx', sa.Integer(), nullable=False),
    sa.Column('LastUpdated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta_data')
    # ### end Alembic commands ###
