"""upload_info table

Revision ID: a9ee66fc37ce
Revises: 
Create Date: 2024-04-01 09:42:44.842031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ee66fc37ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.Column('month', sa.String(length=64), nullable=False),
    sa.Column('year', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_info_filename'), ['filename'], unique=True)
        batch_op.create_index(batch_op.f('ix_upload_info_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_info_upload_date'), ['upload_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_info_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_info_year'))
        batch_op.drop_index(batch_op.f('ix_upload_info_upload_date'))
        batch_op.drop_index(batch_op.f('ix_upload_info_month'))
        batch_op.drop_index(batch_op.f('ix_upload_info_filename'))

    op.drop_table('upload_info')
    # ### end Alembic commands ###
