"""empty message

Revision ID: aa80245173a3
Revises: 
Create Date: 2024-07-01 16:26:15.035968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa80245173a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crime_data',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('IncidentNum', sa.Integer(), nullable=False),
    sa.Column('IncidentDate', sa.Date(), nullable=True),
    sa.Column('TimeOccurred', sa.DateTime(), nullable=True),
    sa.Column('SLMPDOffense', sa.String(length=240), nullable=True),
    sa.Column('NIBRSCode', sa.String(length=64), nullable=True),
    sa.Column('NIBRSCat', sa.String(length=64), nullable=True),
    sa.Column('NIBRSOffenseType', sa.String(length=120), nullable=True),
    sa.Column('SRS_UCR', sa.Float(), nullable=True),
    sa.Column('CrimeGrade', sa.String(length=64), nullable=True),
    sa.Column('PrimaryLocation', sa.String(length=120), nullable=True),
    sa.Column('SecondaryLocation', sa.String(length=120), nullable=True),
    sa.Column('District', sa.String(length=120), nullable=True),
    sa.Column('Neighborhood', sa.String(length=120), nullable=True),
    sa.Column('NeighborhoodNum', sa.String(length=64), nullable=True),
    sa.Column('Latitude', sa.Float(), nullable=True),
    sa.Column('Longitude', sa.Float(), nullable=True),
    sa.Column('Supplemented', sa.Boolean(), nullable=True),
    sa.Column('SupplementDate', sa.Date(), nullable=True),
    sa.Column('VictimNum', sa.Float(), nullable=True),
    sa.Column('FirearmUsed', sa.Boolean(), nullable=True),
    sa.Column('IncidentNature', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('crime_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crime_data_District'), ['District'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_data_FirearmUsed'), ['FirearmUsed'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_data_IncidentDate'), ['IncidentDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_data_IncidentNature'), ['IncidentNature'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_data_IncidentNum'), ['IncidentNum'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_data_NIBRSCat'), ['NIBRSCat'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_data_NIBRSCode'), ['NIBRSCode'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_data_NIBRSOffenseType'), ['NIBRSOffenseType'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_data_Neighborhood'), ['Neighborhood'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_data_NeighborhoodNum'), ['NeighborhoodNum'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_data_SupplementDate'), ['SupplementDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_data_Supplemented'), ['Supplemented'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_data_TimeOccurred'), ['TimeOccurred'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_data_VictimNum'), ['VictimNum'], unique=False)

    op.create_table('meta_data',
    sa.Column('Idx', sa.Integer(), nullable=False),
    sa.Column('LastUpdated', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('Idx')
    )
    op.create_table('raw_data',
    sa.Column('DatePublished', sa.String(length=64), nullable=True),
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('IncidentNum', sa.Integer(), nullable=False),
    sa.Column('IncidentDate', sa.Date(), nullable=True),
    sa.Column('TimeOccurred', sa.DateTime(), nullable=True),
    sa.Column('SLMPDOffense', sa.String(length=240), nullable=True),
    sa.Column('NIBRSCode', sa.String(length=64), nullable=True),
    sa.Column('NIBRSCat', sa.String(length=64), nullable=True),
    sa.Column('NIBRSOffenseType', sa.String(length=120), nullable=True),
    sa.Column('SRS_UCR', sa.Float(), nullable=True),
    sa.Column('CrimeGrade', sa.String(length=64), nullable=True),
    sa.Column('PrimaryLocation', sa.String(length=120), nullable=True),
    sa.Column('SecondaryLocation', sa.String(length=120), nullable=True),
    sa.Column('District', sa.String(length=120), nullable=True),
    sa.Column('Neighborhood', sa.String(length=120), nullable=True),
    sa.Column('NeighborhoodNum', sa.String(length=64), nullable=True),
    sa.Column('Latitude', sa.Float(), nullable=True),
    sa.Column('Longitude', sa.Float(), nullable=True),
    sa.Column('Supplemented', sa.Boolean(), nullable=True),
    sa.Column('SupplementDate', sa.Date(), nullable=True),
    sa.Column('VictimNum', sa.Float(), nullable=True),
    sa.Column('FirearmUsed', sa.Boolean(), nullable=True),
    sa.Column('IncidentNature', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('raw_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_data_District'), ['District'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_data_FirearmUsed'), ['FirearmUsed'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_data_IncidentDate'), ['IncidentDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_data_IncidentNature'), ['IncidentNature'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_data_IncidentNum'), ['IncidentNum'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_data_NIBRSCat'), ['NIBRSCat'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_data_NIBRSCode'), ['NIBRSCode'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_data_NIBRSOffenseType'), ['NIBRSOffenseType'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_data_Neighborhood'), ['Neighborhood'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_data_NeighborhoodNum'), ['NeighborhoodNum'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_data_SupplementDate'), ['SupplementDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_data_Supplemented'), ['Supplemented'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_data_TimeOccurred'), ['TimeOccurred'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_data_VictimNum'), ['VictimNum'], unique=False)

    op.create_table('unfounded_data',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('IncidentNum', sa.Integer(), nullable=False),
    sa.Column('IncidentDate', sa.Date(), nullable=True),
    sa.Column('TimeOccurred', sa.DateTime(), nullable=True),
    sa.Column('SLMPDOffense', sa.String(length=240), nullable=True),
    sa.Column('NIBRSCode', sa.String(length=64), nullable=True),
    sa.Column('NIBRSCat', sa.String(length=64), nullable=True),
    sa.Column('NIBRSOffenseType', sa.String(length=120), nullable=True),
    sa.Column('SRS_UCR', sa.Float(), nullable=True),
    sa.Column('CrimeGrade', sa.String(length=64), nullable=True),
    sa.Column('PrimaryLocation', sa.String(length=120), nullable=True),
    sa.Column('SecondaryLocation', sa.String(length=120), nullable=True),
    sa.Column('District', sa.String(length=120), nullable=True),
    sa.Column('Neighborhood', sa.String(length=120), nullable=True),
    sa.Column('NeighborhoodNum', sa.String(length=64), nullable=True),
    sa.Column('Latitude', sa.Float(), nullable=True),
    sa.Column('Longitude', sa.Float(), nullable=True),
    sa.Column('Supplemented', sa.Boolean(), nullable=True),
    sa.Column('SupplementDate', sa.Date(), nullable=True),
    sa.Column('VictimNum', sa.Float(), nullable=True),
    sa.Column('FirearmUsed', sa.Boolean(), nullable=True),
    sa.Column('IncidentNature', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('unfounded_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unfounded_data_District'), ['District'], unique=False)
        batch_op.create_index(batch_op.f('ix_unfounded_data_FirearmUsed'), ['FirearmUsed'], unique=False)
        batch_op.create_index(batch_op.f('ix_unfounded_data_IncidentDate'), ['IncidentDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_unfounded_data_IncidentNature'), ['IncidentNature'], unique=False)
        batch_op.create_index(batch_op.f('ix_unfounded_data_IncidentNum'), ['IncidentNum'], unique=False)
        batch_op.create_index(batch_op.f('ix_unfounded_data_NIBRSCat'), ['NIBRSCat'], unique=False)
        batch_op.create_index(batch_op.f('ix_unfounded_data_NIBRSCode'), ['NIBRSCode'], unique=False)
        batch_op.create_index(batch_op.f('ix_unfounded_data_NIBRSOffenseType'), ['NIBRSOffenseType'], unique=False)
        batch_op.create_index(batch_op.f('ix_unfounded_data_Neighborhood'), ['Neighborhood'], unique=False)
        batch_op.create_index(batch_op.f('ix_unfounded_data_NeighborhoodNum'), ['NeighborhoodNum'], unique=False)
        batch_op.create_index(batch_op.f('ix_unfounded_data_SupplementDate'), ['SupplementDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_unfounded_data_Supplemented'), ['Supplemented'], unique=False)
        batch_op.create_index(batch_op.f('ix_unfounded_data_TimeOccurred'), ['TimeOccurred'], unique=False)
        batch_op.create_index(batch_op.f('ix_unfounded_data_VictimNum'), ['VictimNum'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unfounded_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unfounded_data_VictimNum'))
        batch_op.drop_index(batch_op.f('ix_unfounded_data_TimeOccurred'))
        batch_op.drop_index(batch_op.f('ix_unfounded_data_Supplemented'))
        batch_op.drop_index(batch_op.f('ix_unfounded_data_SupplementDate'))
        batch_op.drop_index(batch_op.f('ix_unfounded_data_NeighborhoodNum'))
        batch_op.drop_index(batch_op.f('ix_unfounded_data_Neighborhood'))
        batch_op.drop_index(batch_op.f('ix_unfounded_data_NIBRSOffenseType'))
        batch_op.drop_index(batch_op.f('ix_unfounded_data_NIBRSCode'))
        batch_op.drop_index(batch_op.f('ix_unfounded_data_NIBRSCat'))
        batch_op.drop_index(batch_op.f('ix_unfounded_data_IncidentNum'))
        batch_op.drop_index(batch_op.f('ix_unfounded_data_IncidentNature'))
        batch_op.drop_index(batch_op.f('ix_unfounded_data_IncidentDate'))
        batch_op.drop_index(batch_op.f('ix_unfounded_data_FirearmUsed'))
        batch_op.drop_index(batch_op.f('ix_unfounded_data_District'))

    op.drop_table('unfounded_data')
    with op.batch_alter_table('raw_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_data_VictimNum'))
        batch_op.drop_index(batch_op.f('ix_raw_data_TimeOccurred'))
        batch_op.drop_index(batch_op.f('ix_raw_data_Supplemented'))
        batch_op.drop_index(batch_op.f('ix_raw_data_SupplementDate'))
        batch_op.drop_index(batch_op.f('ix_raw_data_NeighborhoodNum'))
        batch_op.drop_index(batch_op.f('ix_raw_data_Neighborhood'))
        batch_op.drop_index(batch_op.f('ix_raw_data_NIBRSOffenseType'))
        batch_op.drop_index(batch_op.f('ix_raw_data_NIBRSCode'))
        batch_op.drop_index(batch_op.f('ix_raw_data_NIBRSCat'))
        batch_op.drop_index(batch_op.f('ix_raw_data_IncidentNum'))
        batch_op.drop_index(batch_op.f('ix_raw_data_IncidentNature'))
        batch_op.drop_index(batch_op.f('ix_raw_data_IncidentDate'))
        batch_op.drop_index(batch_op.f('ix_raw_data_FirearmUsed'))
        batch_op.drop_index(batch_op.f('ix_raw_data_District'))

    op.drop_table('raw_data')
    op.drop_table('meta_data')
    with op.batch_alter_table('crime_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crime_data_VictimNum'))
        batch_op.drop_index(batch_op.f('ix_crime_data_TimeOccurred'))
        batch_op.drop_index(batch_op.f('ix_crime_data_Supplemented'))
        batch_op.drop_index(batch_op.f('ix_crime_data_SupplementDate'))
        batch_op.drop_index(batch_op.f('ix_crime_data_NeighborhoodNum'))
        batch_op.drop_index(batch_op.f('ix_crime_data_Neighborhood'))
        batch_op.drop_index(batch_op.f('ix_crime_data_NIBRSOffenseType'))
        batch_op.drop_index(batch_op.f('ix_crime_data_NIBRSCode'))
        batch_op.drop_index(batch_op.f('ix_crime_data_NIBRSCat'))
        batch_op.drop_index(batch_op.f('ix_crime_data_IncidentNum'))
        batch_op.drop_index(batch_op.f('ix_crime_data_IncidentNature'))
        batch_op.drop_index(batch_op.f('ix_crime_data_IncidentDate'))
        batch_op.drop_index(batch_op.f('ix_crime_data_FirearmUsed'))
        batch_op.drop_index(batch_op.f('ix_crime_data_District'))

    op.drop_table('crime_data')
    # ### end Alembic commands ###
